name: flutter_chat_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase - Updated to latest versions
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # State Management
  provider: ^6.1.1

  # Dependency Injection (Bonus)
  get_it: ^7.6.4

  # Value equality
  equatable: ^2.0.5

  # Functional Programming
  dartz: ^0.10.1

  # For date formatting
  intl: ^0.19.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
